<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post">
            <div class="modal-body">

                <div>
                    <?php echo $_GET['check_in'];
                    echo $_GET['check_out']; ?>

                    <input type="hidden" name="id" class="form-control" id="id">
                    <input id="newId">
                    <input type="hidden" name="check_in"  class="form-control" id="check_in" value="<?php echo $_GET['check_in'];
                    ?>">
                    <input type="hidden" class="form-control" id="check_out" placeholder="Estera" value="<?php echo $_GET['check_out'];
                    ?>">
                </div>
                <div class="form-group">
                    <label for="fName">First Name</label>
                    <input type="text" class="form-control" id="fName" placeholder="Estera">
                </div>
                <div class="form-group">
                    <label for="lName">Last Name</label>
                    <input type="text" class="form-control" id="lName" placeholder="Maftei">
                </div>
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" placeholder="name@example.com">
                </div>
                <div class="form-group">
                    <label for="children">Children</label>
                    <input type="number" min="0" class="form-control" id="children" placeholder="1">
                </div>
                <div class="form-group">
                    <label for="adults">Adult</label>
                    <input type="number" min="0" class="form-control" id="adults" placeholder="1">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Confirm</button>
            </div>
            </form>
        </div>
    </div>
</div>