<!DOCTYPE html>
<html lang="en">
<?php require 'partials/layout/head.phtml'?>

<body>

<?php require 'partials/layout/header.phtml'?>

<div>
    <form action="/hotels">
        <label for="start">Check In:</label>
        <input type="date" id="start" name="check_in"
        <label for="start">Check Out:</label>
        <input type="date" id="start" name="check_out">
        <button type="submit">Find Hotels</button>
    </form>
</div>
<?php require 'partials/layout/footer.phtml'?>

</body>
</html>